- client/.prettierrc
- client/src/App.tsx
- client/src/components/common/layout.tsx
- client/src/components/example/counter.tsx
- client/src/containers/counter-container.tsx
- client/src/index.tsx
- client/src/store/counter.ts
- client/src/store/index.ts
리덕스 사가, 툴킷을 적용한 카운터 예시코드 작성
closes #9 
- 카운터 예제 코드 관련 컴포넌트, 컨테이너 컴포넌트 작성
- 리덕스 사가 비동기 코드 작성
- 리덕스 툴킷 적용
> Feature/#9 리덕스 예시 코드 작성

- .github/workflows/deploy.yml
- .github/workflows/lint-check.yml
- appspec.yml
- scripts/after-deploy.sh
- scripts/before-deploy.sh
- server/package.json
자동 배포를 위한 github workflow 작성
- #16 
* deploy.yml 추가
* server 파일 빌드를 위한 `build`, `prebulid` script 추가
> FEATURE/#16 자동 배포를 위한 github workflow 작성

- server/package.json
- server/src/config/constants.ts
- server/src/controllers/auth.ts
- server/src/controllers/user.ts
- server/src/middlewares/testMiddleware.ts
- server/src/middlewares/validateToken.ts
- server/src/models/user.ts
- server/src/repositories/user.ts
- server/src/routes/auth/github/index.ts
- server/src/routes/auth/index.ts
- server/src/services/auth.ts
- server/src/services/user.ts
- server/src/utils/jwt.ts
- server/src/validation/auth.ts
- server/yarn.lock
깃허브 OAuth
- #35 
* jwt 모듈 리프레시 토큰 이름 상수로 변경
* Github OAuth API
* 인증 관련 요청에서 `userId` 까지 반환하도록 변경
* 서버 내에서 요청을 보내는 `node-fetch` 모듈을 설치했습니다.
* 테스트 요령
1. GET /api/auth/github 요청
`url`이 날아오니, 브라우저로 열어서 주소창의 code를 따옵니다.
2. POST /api/auth/github 요청
`code`를 Body에 넣고 요청을 보냅니다. 코드 하나당 한번의 요청만 가능합니다. 회원가입이 되어있지 않다면, 회원가입을, 회원가입이 되어있다면 로그인을 자동으로 실행하고 토큰을 반환합니다.
> Feature/#35 OAuth

- client/src/components/layout/footer.tsx
- client/src/components/layout/index.tsx
- client/src/pages/__test__/not-found-page.test.tsx
- client/src/pages/not-found-page.tsx
- client/src/styles/styled.d.ts
- client/src/styles/theme.tsx
너허무 간단하게 끝나버린 정적 페이지 생성 피알입니다.
- #39 
- 404 페이지 스타일링 수정
- 푸터 공지사항/이용약관 등 링크 target blank 추가
- 404 페이지 디자인에 대해 고민을 하다가 마땅한게 아직 잘 안 떠올라서 그냥 404-낫파운드로 했습니다. 좋은 아이디어 있으면 말해주세요~
- 폰트가 정상적으로 안 나온다면 원우님 피알에서 고쳐질 것입니다!! 지금 확인해보고 싶다면 원우님 브랜치에서 파일을 받아와서 다시 올려놓겠습니다 ~!
없음
> Feature/#39 정적 페이지 생성

- server/src/models/item.ts
썸네일 url이 varchar(45)보다 길어서 데이터 타입을 TEXT로 변경했습니다
- #57 
- Items.thumbnail의 데이터 타입을 VARCHAR(45)에서 TEXT로 변경했습니다.
> Feature/#57 썸네일 데이터 타입 변경

- client/.eslintrc.json
- client/package.json
- client/src/containers/login-container.tsx
- client/src/containers/signup-container.tsx
- client/src/index.tsx
- client/src/store/auth.ts
- client/src/store/index.ts
- client/src/store/loading.ts
- client/src/utils/saga-utils/index.ts
- client/yarn.lock
사가 커스텀 함수 만들기
로딩 스토어하나에서 관리
#51 
전체적으로 리덕스 관련된 코드 거의 바뀜
지금 커스텀함수는 데이터를 받아오고 에러처리하는 역할밖에 못함
ex) 카테고리 받아오기, 글 받아오기
커스텀함수 더 필요하면 더 만들기
> Feature/#51 사가 커스텀 함수 만들기 + 로딩

- client/.eslintrc.json
- client/src/App.tsx
- client/src/components/item/index.tsx
- client/src/components/item/item-list.tsx
- client/src/components/smart-menu/index.tsx
- client/src/containers/item-container.tsx
- client/src/pages/index.ts
- client/src/pages/item-detail-page.tsx
- client/src/pages/main-page.tsx
- client/src/styles/theme.tsx
- client/src/types/item.ts
- client/src/utils/index.ts
아이템 컴포넌트 UI를 개발합니다.
- #49 
- 아이템 컴포넌트 생성
- 아이템 리스트 컴포넌트 생성
- 상태 뱃지 추가
- 좋아요 아이콘 추가
- 마우스 올렸을 때 인터랙션 추가
- UI만 구현했습니다 ~
- 아이템 받아오기 백엔드 기능 연동
- 아이템 리스트 - 필터 기능 등
> Feature/#49 아이템 컴포넌트 UI

- client/src/App.tsx
- client/src/components/auth/form.tsx
- client/src/components/item/item-list.tsx
- client/src/containers/login-container.tsx
- client/src/containers/signup-container.tsx
- client/src/index.tsx
- client/src/pages/auth-page.tsx
- client/src/pages/index.ts
- client/src/store/auth.ts
- client/src/types/auth.ts
- client/src/utils/api/auth.ts
- server/src/config/constants.ts
- server/src/config/db.ts
- server/src/controllers/auth.ts
- 깃허브 로그인 구현
- id, password length 수정
- 서버 json반환값 수정
- #59 
리덕스 스토어 
깃허브 pr 이슈닫기 참고 블로그
https://sundries-in-myidea.tistory.com/90
> Feature/#59 oauth 로그인 구현 + 서버 코드 일부 수정

- server/package.json
- server/src/controllers/search.ts
- server/src/models/item.ts
- server/src/repositories/search.ts
- server/src/routes/index.ts
- server/src/routes/search/index.ts
- server/src/services/search.ts
- server/yarn.lock
검색어 자동완성 백엔드 API를 개발했습니다
- #66 
- korean-regexp 패키지 추가
- 검색어 자동완성 API 추가
- sequelize item 모델 오타 수정, sale_count 컬럼 추가
- 자음 검색도 됩니다
- 프론트와 연동
> Feature/#66 검색어 자동완성 API

- client/src/components/item/item-list-wrapper.tsx
- client/src/components/item/item-list.tsx
- client/src/containers/item-list-container.tsx
- client/src/store/auth.ts
- client/src/store/items.ts
- client/src/types/error.ts
- client/src/types/item.ts
- client/src/utils/api/items.ts
- server/src/controllers/items.ts
- server/src/loaders/sequelize.ts
- server/src/models/item.ts
- server/src/models/user.ts
- server/src/repositories/items.ts
- server/src/services/items.ts
db 아이템 설정을 변경하고 아이템 옵션을 가공 넘겨줌, + 아이템페이지카운트 추가 + 프론트 적용
resolve #89 
세부사항은 논의가 조금 필요
ex) 크론탭 몇분마다 할건지, best는 몇개인지, new는 몇개인지
----------------------------------------------------
isNew는 6개월로 설정해놨음. 바꾸고 싶으면 바꿔도 괜찮아요!!
best 업데이트(limit 30 a는 서브쿼리의 이름을정하지 않으면 오류를 뱉어서... 이것도 리미트를 몇개로 할건지, 시간은 어떻게 할건지 팀원과 의논)
UPDATE Items SET is_best = CASE 
WHEN id IN (select id from (select id from items order by sale_count desc limit 30)a) THEN 1 
ELSE 0
END;
크론탭 만드는 방법 -- 문서화할것
crontab-e
5 * * * * /home/ubuntu/deploy.sh
sudo mysql
use testdb;
UPDATE Items SET is_best = CASE 
WHEN id IN (select id from (select id from items order by sale_count desc limit 30)a) THEN 1 
ELSE 0
END;
exit
chmod +x file_name
그림님 세미나보고 인터페이스 상속같은걸 해봤는데 맞게했나 모르겠네요. 궁금하거나 틀린거있으면 말해주세요
하다가 user varchar오류뜨면 sync를 alter지우시면 됩니다. 보통 db정보 …
> Feature/#89 설정 변경 및 아이템 옵션 추가 + 아이템전체개수 + 크론탭

- client/src/App.tsx
- client/src/components/auth/form.tsx
- client/src/components/common/menu-header.tsx
- client/src/components/item-detail/index.tsx
- client/src/components/item-detail/info-section.tsx
- client/src/components/item/index.tsx
- client/src/components/my/inquiry-period.tsx
- client/src/components/my/my-bar.tsx
- client/src/components/my/my-order-list.tsx
- client/src/components/my/my-order.tsx
- client/src/components/my/my-status-bar.tsx
- client/src/containers/item-detail-container.tsx
- client/src/containers/my-order-list-container.tsx
- client/src/lib/router/path-validation.ts
- client/src/lib/woowahan-components/configs/react-props.ts
- client/src/pages/index.ts
- client/src/pages/my-order-list-page.tsx
- client/src/store/item.ts
- client/src/styles/theme.tsx
- client/src/types/item.ts
- client/src/utils/api/item.ts
- client/src/utils/date.ts
- server/src/controllers/items.ts
- server/src/models/index.ts
- server/src/models/score.ts
- server/src/repositories/items.ts
- server/src/routes/items/index.ts
- server/src/services/items.ts
- server/src/utils/error/error-handler.ts
제품 상세정보 불러오기 API
- #101 
* 제품상세정보 불러오기 API
* 제품상세정보 불러오기 API - FE 연동
* 장바구니 추가, 상품 구매 버튼에 껍데기 함수 적용
> Feature/#101 제품 상세정보 불러오기 API

- client/src/App.tsx
- client/src/components/common/grid-form.tsx
- client/src/components/common/layout/index.tsx
- client/src/components/common/price-calculator.tsx
- client/src/components/common/table.tsx
- client/src/components/common/text-button.tsx
- client/src/components/order/index.tsx
- client/src/components/order/table-section.tsx
- client/src/pages/index.ts
- client/src/pages/order-page.tsx
- client/src/utils/validation/order-validation.ts
주문하기 페이지 UI
- #106 
* 그리드폼 공용 컴포넌트
* 테이블 컴포넌트
* price-calculator 컴포넌트
* 레이아웃 align-items 제거
* 주문 Form Validation
* 주문하기 페이지 UI
테이블과 그리드폼에는 컴포넌트를 넣어줄 수 있습니다.
현재 페이지 연결이 안 되어있어서 http://localhost:9000/pay로 접속하시면 페이지를 확인하실 수 있습니다
* 그리드폼 사용
```jsx
<GridForm titles={['주문하시는 분*', '전화번호*']}>
<InputWrapper>
<input minLength={2} name="user" value={user} onChange={onChange} />
<InputErrorMessage>{userError}</InputErrorMessage>
</InputWrapper>
<InputWrapper>
<input name="phone" value={phone} onChange={onChange} />
<InputErrorMessage>{phoneError}</InputErrorMessage>
</InputWrapper>
</GridForm>
```
가장 서열이 높은 자식이 한 줄씩 차지합니다. 그래서 row당 하나의 컴포넌트를 넘겨줘야 합니다.
* 테이블 사용
```jsx
<Table headers={tableHeaders}>
{orderItems.map(item => {
const { id, title, thumbnail, count, price } = item;
return (
<Fragment …
```
> Feature/#106 주문하기 페이지 UI

- client/src/utils/validation/order-validation.ts
- server/src/config/constants.ts
- server/src/controllers/orders.ts
- server/src/models/order.ts
- server/src/repositories/orders.ts
- server/src/routes/orders/index.ts
- server/src/services/orders.ts
- server/src/validation/orders.ts
주문하기 API
- #121 
* Order 테이블 스키마 타입 변경
* 주문하기 API validation 및 클라이언트 validation 동기화
* 주문하기 API
포스트맨에 주문하기 추가해뒀습니다. 테스트하시길 바랍니다. 테스트를 하시면 좋은점을 알기위해서는 먼저 테스트를 왜 해야하는가 부터 시작해야하는데, 궁극적인 목표는 잘 작동하는 깔끔한 코드를 얻기 위해서입니다. 그렇다면 왜 테스트를 하냐하면, 깔끔한 잘 작동하는 깔끔한 코드를 얻을 수 있기 위함일까요? 테스트를 쉽게 하기 위해서는 어플리케이션 코드를 테스트하기 쉽게 짜야합니다. 결국 테스트 코드를 짜기 위해 노력한다면 어플리케이션 코드가 깔끔해진다는 말입니다. (...이하 생략)
* 주문하기 페이지 API 연동
> Feature/#121 주문하기 API

- client/src/App.tsx
- client/src/components/my/my-address/my-address-form.tsx
- client/src/components/my/my-address/my-address-table.tsx
- client/src/components/my/my-order-table.tsx
- client/src/containers/my-address-container.tsx
- client/src/containers/my-order-list-container.tsx
- client/src/pages/index.ts
- client/src/pages/my-address-page.tsx
- client/src/saga/__test__/address.test.ts
- client/src/saga/__test__/category.test.ts
- client/src/saga/address.ts
- client/src/saga/category.ts
- client/src/store/address.ts
- client/src/store/index.ts
- client/src/store/loading.ts
- client/src/types/address.ts
- client/src/utils/api/address.ts
- server/src/controllers/address.ts
- server/src/repositories/address.ts
- server/src/services/address.ts
- server/src/utils/error/error-handler.ts
배송지 관리 프론트엔드 코드 + 사가 + 테스트코드
#129 
마이페이지 배송지관리 create, delete, read
> Feature/#129 배송지관리 프론트엔드

- client/src/components/smart-menu/index.tsx
- client/src/components/smart-menu/large-menu.tsx
- client/src/components/smart-menu/medium-menu.tsx
- client/src/constants/index.ts
- client/src/utils/checkWidth.ts
스마트 메뉴가 사용자의 예측대로 동작하게 변경했습니다
- #173 
- 데스크탑에서는 hover, 모바일에서는 클릭으로 작동하게 변경했습니다
> Feature/#173 스마트 메뉴 작동방식 수정

- client/src/components/cart/index.tsx
- client/src/components/cart/table-section.tsx
- client/src/components/smart-menu/index.tsx
- client/src/components/smart-menu/large-menu.tsx
- client/src/components/smart-menu/medium-menu.tsx
- client/src/utils/checkWidth.ts
장바구니 페이지를 벗어나도 선택 상태가 유지 되던 버그를 수정하고
장바구니 페이지 진입 시 상품이 모두 선택되어있게 변경했습니다.
- #186 
- 장바구니 페이지를 벗어날 시 선택 상태가 초기화 됩니다
- 장바구니 페이지 진입 시 모든 상품이 선택되어 있습니다
> Bug/#186 장바구니 선택 버그 및 수정

- server/src/controllers/address.ts
- server/src/controllers/auth.ts
- server/src/controllers/items.ts
- server/src/controllers/like.ts
- server/src/controllers/orders.ts
- server/src/controllers/search.ts
- server/src/controllers/user.ts
- server/src/models/item.ts
- server/src/repositories/category.ts
- server/src/repositories/items.ts
- server/src/repositories/like.ts
- server/src/repositories/orders.ts
- server/src/repositories/reviews.ts
- server/src/repositories/search.ts
- server/src/routes/auth/index.ts
- server/src/services/auth.ts
- server/src/services/category.ts
- server/src/services/items.ts
- server/src/services/like.ts
- server/src/services/orders.ts
- server/src/services/reviews.ts
- server/src/services/search.ts
- server/src/types/address.ts
- server/src/types/auth.ts
- server/src/utils/error/error-handler.ts
- server/src/validation/address.ts
- server/src/validation/auth.ts
- server/src/validation/orders.ts
백엔드 리팩토링
- #132 
* 전반적으로 repository는 DB 접근 + 단순한 데이터 가공, service는 복잡한 데이터 가공의 방향으로 바꾸었습니다.
* 타입의 간단한 정리
* validation empty 항목 추가
* 테스트용 코드 삭제
* 불필요한 Req 테스트 삭제
* 병렬적 실행이 가능한 항목은 `Promise.all` 적용
* 에러 처리 형식 변경
* 성공응답 빈 객체 -> 완전히 빈 응답으로 변경
* 아이템은 이미 괴물이라 손을 많이 못 댔습니다..
> Feature/#132 백엔드 리팩토링

- client/src/components/common/layout/footer.tsx
- client/src/components/common/layout/header.tsx
- client/src/components/common/navbar.tsx
- client/src/components/item-detail/detail-wrapper.tsx
- client/src/components/smart-menu/index.tsx
- client/src/containers/item-detail-container.tsx
- client/src/containers/main-item-container.tsx
- client/src/containers/my-address-container.tsx
- client/src/containers/my-order-list-container.tsx
- client/src/containers/navbar-container.tsx
- client/src/containers/order-container.tsx
- client/src/containers/search-item-container.tsx
- client/src/containers/signin-container.tsx
- client/src/containers/signup-container.tsx
- client/src/containers/smart-menu-container.tsx
리액트 최적화
#154 
useSelector 최적화 : 여러 store에서 가져오기 때문에 shallowEqual옵션을 줘서 얕은비교를 해서 그 부분이 바뀌었을때만 가져온다.
React.memo 최적화 : props가 바뀌는 경우에만 바뀌게 하는게 memo인데 생각보다 잘 적용되지 않아서 헤더, 푸터, 네브바 정도만 적용을 했다.
생각보다 최적화가 잘 안됩니다. useCallback, useMemo가 적용되지 않은부분들도 있고 이유를 못찾는 경우도 많이 있네요
시간이 있다면 같이 해보면 좋겠지만 일단은 다음을 기약해야될것같습니다.
> Feature/#154 리액트 최적화

- client/src/components/common/navbar.tsx
- client/src/components/item-detail/item-info.tsx
- client/src/components/my/my-address/my-address-form.tsx
- client/src/components/my/my-address/my-address-table.tsx
- client/src/components/order/index.tsx
- client/src/components/order/table-section.tsx
- client/src/containers/item-detail-container.tsx
- client/src/containers/my-address-container.tsx
- client/src/containers/order-container.tsx
- client/src/store/item.ts
- client/src/types/address.ts
- client/src/types/item.ts
- client/src/utils/api/address.ts
- client/src/utils/validation/order-validation.ts
- server/src/controllers/address.ts
- server/src/models/address.ts
- server/src/repositories/address.ts
- server/src/repositories/items.ts
- server/src/services/address.ts
- server/src/services/items.ts
- server/src/types/address.ts
- server/src/validation/address.ts
주말 백엔드 작업
#191 
할인율 오류있던 부분 수정
주문부분에 주소 라이브러리 적용
반응형 css 수정
> Feature/#191 백엔드 개선사항 수정

- client/package.json
- client/src/constants/index.ts
- client/src/containers/item-detail-container.tsx
- client/src/index.tsx
- client/src/pages/cart-page.tsx
- client/src/pages/item-list-page.tsx
- client/src/pages/main-page.tsx
- client/src/pages/my-address-page.tsx
- client/src/pages/my-order-list-page.tsx
- client/src/pages/not-found-page.tsx
- client/src/pages/order-page.tsx
- client/src/pages/signin-page.tsx
- client/src/pages/signup-page.tsx
- client/yarn.lock
리액트 타이틀 변경
#196 
리액트의 타이틀을 변경합니다
> Feature/#196 react title 적용

- client/src/components/cart/index.tsx
- client/src/components/common/navbar.tsx
- client/src/components/common/price-calculator.tsx
- client/src/components/search-bar/index.tsx
사파리에서 적용되지 않는 `gap` 스타일 조정
- #192 
- `gap`을 `margin`으로 변경
- 네브바 style 버그 있어서 수정
> Feature/#192 사파리 적용되지 않는 style 수정

- client/src/components/smart-menu/index.tsx
스마트 메뉴 이벤트를 수정했습니다
- #203 
- 태블릿 크기에서의 이벤트를 변경했습니다
> Feature/#203 스마트 메뉴 오류 수정

- client/src/components/cart/index.tsx
- client/src/components/common/navbar.tsx
- client/src/containers/item-detail-container.tsx
- client/src/containers/navbar-container.tsx
- client/src/containers/order-container.tsx
- client/src/index.tsx
- client/src/store/cart.ts
- client/src/store/index.ts
- client/src/utils/cart-generator.ts
장바구니 count부분에 문제가 생겨서 전역으로 관리
#206 
전역으로 빼는거 말고는 바뀐거 없습니다.
cartvalidate할때 local에서 카트를 가져오는데 그부분을 전역변수로 넣으니 뭔지 모를 에러가 나더라구요.. 
그래서 그냥 그부분은 로컬에서 가져옵니다.
지금 구조를 처음부터 리덕스 형태로 싹 다 바꿀수가 없어서 동작만 제대로 하게 해놨습니다.
> Feature/#206 장바구니를 redux에서 관리
